/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

import controller.DatabaseManager;
import controller.Product;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 * @author bneveu218
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    public NewJFrame() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemEdit = new javax.swing.JDialog();
        addItem1 = new javax.swing.JPanel();
        newNameField = new javax.swing.JTextField();
        newSubmitItem = new javax.swing.JButton();
        newEnterLabel = new javax.swing.JLabel();
        newQtyField = new javax.swing.JTextField();
        newNumField = new javax.swing.JTextField();
        newPriceField = new javax.swing.JTextField();
        newNameLabel = new javax.swing.JLabel();
        newNumLabel = new javax.swing.JLabel();
        newPriceLabel = new javax.swing.JLabel();
        newQtyLabel = new javax.swing.JLabel();
        newItemDesc = new javax.swing.JLabel();
        itemView = new javax.swing.JDialog();
        addItem2 = new javax.swing.JPanel();
        viewLabel = new javax.swing.JLabel();
        viewName = new javax.swing.JLabel();
        viewNum = new javax.swing.JLabel();
        viewPrice = new javax.swing.JLabel();
        viewQty = new javax.swing.JLabel();
        viewNameLabel = new javax.swing.JLabel();
        viewNumLabel = new javax.swing.JLabel();
        viewPriceLabel = new javax.swing.JLabel();
        viewQtyLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addItem = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        submitItem = new javax.swing.JButton();
        enterLabel = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        numField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        updateItem = new javax.swing.JPanel();
        selectLabel = new javax.swing.JLabel();
        selectBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        lookupField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        resultScroll = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList<>();
        editBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();

        itemEdit.setModal(true);

        addItem1.setBackground(new java.awt.Color(51, 153, 255));

        newNameField.setBackground(new java.awt.Color(240, 240, 240));
        newNameField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        newNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameFieldActionPerformed(evt);
            }
        });

        newSubmitItem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newSubmitItem.setText("Submit");
        newSubmitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubmitItemActionPerformed(evt);
            }
        });

        newEnterLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newEnterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newEnterLabel.setText("Please enter changes for the following item:");
        newEnterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newEnterLabel.setOpaque(true);

        newQtyField.setBackground(new java.awt.Color(240, 240, 240));
        newQtyField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newQtyField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        newQtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQtyFieldActionPerformed(evt);
            }
        });

        newNumField.setBackground(new java.awt.Color(240, 240, 240));
        newNumField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newNumField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        newNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNumFieldActionPerformed(evt);
            }
        });

        newPriceField.setBackground(new java.awt.Color(240, 240, 240));
        newPriceField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newPriceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        newPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPriceFieldActionPerformed(evt);
            }
        });

        newNameLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newNameLabel.setText("New name:");
        newNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newNameLabel.setOpaque(true);

        newNumLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newNumLabel.setText("New number:");
        newNumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newNumLabel.setOpaque(true);

        newPriceLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPriceLabel.setText("New price:");
        newPriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newPriceLabel.setOpaque(true);

        newQtyLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newQtyLabel.setText("New quantity:");
        newQtyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newQtyLabel.setOpaque(true);

        newItemDesc.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        newItemDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newItemDesc.setText("Purina One Cat Food 12 oz");
        newItemDesc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newItemDesc.setOpaque(true);

        javax.swing.GroupLayout addItem1Layout = new javax.swing.GroupLayout(addItem1);
        addItem1.setLayout(addItem1Layout);
        addItem1Layout.setHorizontalGroup(
                addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItem1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newEnterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                        .addGroup(addItem1Layout.createSequentialGroup()
                                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newQtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addItem1Layout.createSequentialGroup()
                                                                .addComponent(newSubmitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(newQtyField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(newPriceField)
                                                        .addComponent(newNumField)
                                                        .addComponent(newNameField)))
                                        .addComponent(newItemDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                                .addContainerGap())
        );
        addItem1Layout.setVerticalGroup(
                addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItem1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newEnterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newNameField)
                                        .addComponent(newNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newQtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newSubmitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout itemEditLayout = new javax.swing.GroupLayout(itemEdit.getContentPane());
        itemEdit.getContentPane().setLayout(itemEditLayout);
        itemEditLayout.setHorizontalGroup(
                itemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 367, Short.MAX_VALUE)
                        .addGroup(itemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(itemEditLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        itemEditLayout.setVerticalGroup(
                itemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 314, Short.MAX_VALUE)
                        .addGroup(itemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(itemEditLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        itemView.setModal(true);

        addItem2.setBackground(new java.awt.Color(51, 153, 255));

        viewLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setText("Here is the info for the item you chose:");
        viewLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewLabel.setOpaque(true);

        viewName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewName.setText("<Name>");
        viewName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewName.setOpaque(true);

        viewNum.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewNum.setText("<Number>");
        viewNum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewNum.setOpaque(true);

        viewPrice.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewPrice.setText("<Price>");
        viewPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewPrice.setOpaque(true);

        viewQty.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewQty.setText("<Quantity>");
        viewQty.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewQty.setOpaque(true);

        viewNameLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewNameLabel.setText("Item name:");
        viewNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewNumLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewNumLabel.setText("Item SKU:");
        viewNumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewPriceLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewPriceLabel.setText("Item price:");
        viewPriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewQtyLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewQtyLabel.setText("Item quantity:");
        viewQtyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addItem2Layout = new javax.swing.GroupLayout(addItem2);
        addItem2.setLayout(addItem2Layout);
        addItem2Layout.setHorizontalGroup(
                addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItem2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(viewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addItem2Layout.createSequentialGroup()
                                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(viewPriceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewNumLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(viewPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewQty, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        addItem2Layout.setVerticalGroup(
                addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItem2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewQty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewQtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout itemViewLayout = new javax.swing.GroupLayout(itemView.getContentPane());
        itemView.getContentPane().setLayout(itemViewLayout);
        itemViewLayout.setHorizontalGroup(
                itemViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 251, Short.MAX_VALUE)
                        .addGroup(itemViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(itemViewLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        itemViewLayout.setVerticalGroup(
                itemViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 226, Short.MAX_VALUE)
                        .addGroup(itemViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(itemViewLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jTabbedPane1.setBackground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        addItem.setBackground(new java.awt.Color(95, 193, 128));

        nameField.setBackground(new java.awt.Color(240, 240, 240));
        nameField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        submitItem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        submitItem.setText("Submit");
        submitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitItemActionPerformed(evt);
            }
        });

        enterLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        enterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterLabel.setText("Please enter item information below:");
        enterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterLabel.setOpaque(true);

        qtyField.setBackground(new java.awt.Color(240, 240, 240));
        qtyField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        qtyField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        qtyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyFieldActionPerformed(evt);
            }
        });

        numField.setBackground(new java.awt.Color(240, 240, 240));
        numField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        numField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFieldActionPerformed(evt);
            }
        });

        priceField.setBackground(new java.awt.Color(240, 240, 240));
        priceField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        priceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name:");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nameLabel.setOpaque(true);

        numLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        numLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numLabel.setText("Number:");
        numLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        numLabel.setOpaque(true);

        priceLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price:");
        priceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        priceLabel.setOpaque(true);

        qtyLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        qtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyLabel.setText("Quantity:");
        qtyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qtyLabel.setOpaque(true);

        javax.swing.GroupLayout addItemLayout = new javax.swing.GroupLayout(addItem);
        addItem.setLayout(addItemLayout);
        addItemLayout.setHorizontalGroup(
                addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                        .addGroup(addItemLayout.createSequentialGroup()
                                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addItemLayout.createSequentialGroup()
                                                                .addComponent(submitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(qtyField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(priceField)
                                                        .addComponent(numField)
                                                        .addComponent(nameField))))
                                .addContainerGap())
        );
        addItemLayout.setVerticalGroup(
                addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(enterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(submitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("                   Add Item                    ", addItem);

        updateItem.setBackground(new java.awt.Color(44, 133, 221));

        selectLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        selectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectLabel.setText("Please select a type to look up the item by:");
        selectLabel.setToolTipText("");
        selectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectLabel.setOpaque(true);

        selectBox.setBackground(new java.awt.Color(240, 240, 240));
        selectBox.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        selectBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Number", "Name", "Price"}));
        selectBox.setToolTipText("");
        selectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBoxActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Enter number:");
        typeLabel.setToolTipText("");
        typeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        typeLabel.setOpaque(true);

        lookupField.setBackground(new java.awt.Color(240, 240, 240));
        lookupField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lookupField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lookupField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupFieldActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("Results found:");
        resultLabel.setToolTipText("");
        resultLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultLabel.setOpaque(true);

        resultList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resultScroll.setViewportView(resultList);

        editBtn.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        infoBtn.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        infoBtn.setText("Delete");
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        delBtn.setText("View Info");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateItemLayout = new javax.swing.GroupLayout(updateItem);
        updateItem.setLayout(updateItemLayout);
        updateItemLayout.setHorizontalGroup(
                updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(updateItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(updateItemLayout.createSequentialGroup()
                                                .addComponent(selectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(selectBox, 0, 94, Short.MAX_VALUE))
                                        .addComponent(resultScroll)
                                        .addGroup(updateItemLayout.createSequentialGroup()
                                                .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updateItemLayout.createSequentialGroup()
                                                                        .addGap(72, 72, 72)
                                                                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lookupField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(updateItemLayout.createSequentialGroup()
                                                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        updateItemLayout.setVerticalGroup(
                updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(updateItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lookupField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(updateItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("                 Update Item                  ", updateItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed

        Object[] selectedObj = resultList.getSelectedValuesList().toArray();
        ArrayList<Product> products = new ArrayList<>();
        for (Object obj : selectedObj) {
            products.add((Product) obj);
        }
        if (products.size() > 0) {
            for (Product p : products) {
                viewName.setText(p.getName());
                viewNum.setText(p.getSku());
                viewPrice.setText(Double.toString(p.getPrice()));
                viewQty.setText(Integer.toString(p.getQuantity()));
                itemView.pack();
                itemView.setVisible(true);
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        Object[] selectedObj = resultList.getSelectedValuesList().toArray();
        ArrayList<Product> products = new ArrayList<>();
        ArrayList<Product> toAdd = DatabaseManager.getProducts();
        for (Object obj : selectedObj) {
            products.add((Product) obj);
        }
        for (Product p : products) {
            System.out.println(p);
            toAdd.removeIf(match -> match.getName().equals(p.getName()));
            DatabaseManager.saveProducts(toAdd);
            JOptionPane.showMessageDialog(this, "Item was deleted.", "Successful Action", JOptionPane.INFORMATION_MESSAGE);
            DefaultListModel list = (DefaultListModel) resultList.getModel();
            list.clear();
        }
    }//GEN-LAST:event_infoBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        Object[] selectedObj = resultList.getSelectedValuesList().toArray();
        ArrayList<Product> products = new ArrayList<>();
        for (Object obj : selectedObj) {
            products.add((Product) obj);
        }
        if (products.size() > 0) {
            for (Product p : products) {
                newNameField.setText(p.getName());
                newNumField.setText(p.getSku());
                newPriceField.setText(Double.toString(p.getPrice()));
                newQtyField.setText(Integer.toString(p.getQuantity()));
                newItemDesc.setText(p.toString());
                itemEdit.pack();
                itemEdit.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item.", "Invalid Selection", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void lookupFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupFieldActionPerformed
        String type = selectBox.getSelectedItem().toString();
        ArrayList<Product> matches = new ArrayList<>();
        if (!lookupField.getText().isEmpty()) {
            if (type.equals("Name")) {
                matches = DatabaseManager.searchByName(lookupField.getText());
            } else if (type.equals("Price")) {
                matches = DatabaseManager.searchByPrice(Double.parseDouble(lookupField.getText()));
            } else if (type.equals("Number")) {
                matches = DatabaseManager.searchBySku(lookupField.getText());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Field empty. Please enter something.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
        }
        DefaultListModel res = new DefaultListModel();
        for (Product p : matches) {
            res.addElement(p);
        }
        resultList.setModel(res);
    }//GEN-LAST:event_lookupFieldActionPerformed

    private void selectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBoxActionPerformed
        typeLabel.setText("Enter " + (selectBox.getSelectedItem().toString().toLowerCase()) + ":");
    }//GEN-LAST:event_selectBoxActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void numFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numFieldActionPerformed

    private void qtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyFieldActionPerformed

    private void submitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitItemActionPerformed
        ArrayList<JTextField> fields = new ArrayList<>();
        fields.add(nameField);
        fields.add(numField);
        fields.add(qtyField);
        fields.add(priceField);
        boolean isValid = true;
        boolean canSubmit = true;
        boolean alreadyExists = false;
        try {
            Integer.parseInt(qtyField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        try {
            Double.parseDouble(priceField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        for (JTextField field : fields) {
            if (canSubmit == true) {
                canSubmit = true;
                if (field.getText().isEmpty()) {
                    System.out.println("empty field");
                    canSubmit = false;
                }
            }
        }
        if (canSubmit) {
            if (isValid) {
                ArrayList<Product> products = DatabaseManager.getProducts();
                for (Product p : products) {
                    if (p.getSku().equals(numField.getText())) {
                        JOptionPane.showMessageDialog(this, "Object with that code already exists.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                        alreadyExists = true;
                    }
                }
                if (!alreadyExists) {
                    String name = nameField.getText();
                    String sku = numField.getText();
                    int qty = Integer.parseInt(qtyField.getText());
                    double price = Double.parseDouble(priceField.getText());
                    Product newProduct = new Product(name, sku, qty, price);
                    products.add(newProduct);
                    DatabaseManager.saveProducts(products);
                    JOptionPane.showMessageDialog(this, "Item was successfully added.", "Successful Action", JOptionPane.INFORMATION_MESSAGE);
                    for (JTextField field : fields) {
                        field.setText("");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "One or more fields is empty. Please fill in these fields.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitItemActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void newSubmitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubmitItemActionPerformed
        Object[] selectedObj = resultList.getSelectedValuesList().toArray();
        ArrayList<Product> products = new ArrayList<>();
        ArrayList<Product> toAdd = DatabaseManager.getProducts();
        for (Object obj : selectedObj) {
            products.add((Product) obj);
        }
        boolean isValid = true;
        boolean canSubmit = true;
        ArrayList<JTextField> fields = new ArrayList<>();
        fields.add(newNameField);
        fields.add(newNumField);
        fields.add(newQtyField);
        fields.add(newPriceField);
        try {
            Integer.parseInt(newQtyField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "New quantity must be a number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        try {
            Double.parseDouble(newPriceField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "New price must be a number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        for (JTextField field : fields) {
            if (canSubmit == true) {
                canSubmit = !field.getText().isEmpty();
            }
        }
        for (Product p : products) {
            if (canSubmit) {
                if (isValid) {
                    String name = newNameField.getText();
                    String sku = newNumField.getText();
                    int qty = Integer.parseInt(newQtyField.getText());
                    double price = Double.parseDouble(newPriceField.getText());
                    Product newProduct = new Product(name, sku, qty, price);
                    toAdd.removeIf(match -> match.getName().equals(p.getName()));
                    toAdd.add(newProduct);
                    DatabaseManager.saveProducts(toAdd);
                    itemEdit.setVisible(false);
                    DefaultListModel list = (DefaultListModel) resultList.getModel();
                    list.clear();
                    JOptionPane.showMessageDialog(this, "Product was updated.", "Successful Edit", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_newSubmitItemActionPerformed

    private void newNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameFieldActionPerformed

    private void newQtyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQtyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newQtyFieldActionPerformed

    private void newNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNumFieldActionPerformed

    private void newPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPriceFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addItem;
    private javax.swing.JPanel addItem1;
    private javax.swing.JPanel addItem2;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JButton infoBtn;
    private javax.swing.JDialog itemEdit;
    private javax.swing.JDialog itemView;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lookupField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel newEnterLabel;
    private javax.swing.JLabel newItemDesc;
    private javax.swing.JTextField newNameField;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JTextField newNumField;
    private javax.swing.JLabel newNumLabel;
    private javax.swing.JTextField newPriceField;
    private javax.swing.JLabel newPriceLabel;
    private javax.swing.JTextField newQtyField;
    private javax.swing.JLabel newQtyLabel;
    private javax.swing.JButton newSubmitItem;
    private javax.swing.JTextField numField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JList<String> resultList;
    private javax.swing.JScrollPane resultScroll;
    private javax.swing.JComboBox<String> selectBox;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JButton submitItem;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel updateItem;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewNameLabel;
    private javax.swing.JLabel viewNum;
    private javax.swing.JLabel viewNumLabel;
    private javax.swing.JLabel viewPrice;
    private javax.swing.JLabel viewPriceLabel;
    private javax.swing.JLabel viewQty;
    private javax.swing.JLabel viewQtyLabel;
    // End of variables declaration//GEN-END:variables
}
